name: "Gradle Build"
on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - uses: actions/upload-artifact@v4
      with:
        name: Upload artifacts
        path: build/libs
